Add header to site
uvchuk/team-project-foodsta pull request #4
Opened 2022-10-30 09:28 UTC by NiedzwiedzIT

2022-10-30 10:25 UTC, uvchuk requested changes
Передивись, дещо треба переробити

2022-10-30 10:25 UTC, uvchuk commented on src/partials/header.html
> +  <nav class="header header__container">
Зміни nav на звичайний дів для контейнеру

2022-10-30 10:25 UTC, uvchuk commented on src/partials/header.html
> +    <ul class="menu">
а ось цей ul з лішками огорни в nav (це для семантики)

2022-10-30 10:25 UTC, uvchuk commented on src/partials/header.html
> +        <a class="menu__link menu__link--current" href="#">home</a>
перейменуй всі посилання на назви наших секцій (Hero, Offerings, Favorites, Customers Say, Subscribe)
і одразу пропишемо якоря для них: href="#hero",  href="#offerings" і т.д.

2022-10-30 10:25 UTC, uvchuk commented on src/sass/_header.scss
> +  box-shadow: 0px 4px 24px var(--box-shadow-header);
можеш для зручності прописти не тільки колір, а усе значення в перемінну

2022-10-30 10:25 UTC, uvchuk commented on src/sass/_header.scss
> +  @media screen and (min-width: 768px) {
Я добавив вам для зручності міксіни для медіа запитів. Замість @media screen and (min-width: 768px)  можна коротко написати @include mobile; (або tablet або dekstop) - так коротше, але це по бажанню

2022-10-30 10:25 UTC, uvchuk commented on src/sass/_header.scss
> +.logo__icon {
задай для цього класу display: block, тоді розмір твого хедеру буде такий як на макеті

2022-10-30 10:25 UTC, uvchuk commented on src/sass/_header.scss
> +.menu__item {
Забери з цих айтемів падінги і дай їх лінкам

2022-10-30 10:25 UTC, uvchuk commented on src/sass/_header.scss
> +.menu__link {
І також для лінків display:inline-block
зауваж також, що лінки мають колір #000000;
для усіх лінків задай для мобілки :active а для таблетки і десктопу :hover :focus

2022-10-30 10:25 UTC, uvchuk commented on src/sass/_header.scss
> +.menu__link--current:focus {
Забери з цього класу hover i focus, просто залиш йому колір і underline

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/partials/header.html
> +  <nav class="header header__container">
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/partials/header.html
> +    <ul class="menu">
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/partials/header.html
> +        <a class="menu__link menu__link--current" href="#">home</a>
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +  box-shadow: 0px 4px 24px var(--box-shadow-header);
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +  @media screen and (min-width: 768px) {
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +.logo__icon {
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +.menu__item {
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +.menu__link {
Пофіксив

2022-10-30 11:58 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +.menu__link--current:focus {
Пофіксив

2022-10-30 15:04 UTC, uvchuk requested changes

2022-10-30 15:04 UTC, uvchuk commented on src/partials/header.html
> +    <nav class="header header__container">
клас header__container перенеси для div вище
у тезі nav повинно бути вкладено тільки ul та 5 li

2022-10-30 15:04 UTC, uvchuk commented on src/sass/_header.scss
> +.menu__link {
@include mobie {
&:active {.......}
}
@include tablet {
&:focus, &:hover {.....}
}

2022-10-31 13:57 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +.menu__link {
Пофіксив

2022-10-31 13:57 UTC, NiedzwiedzIT commented on src/partials/header.html
> +    <nav class="header header__container">
Пофіксив

2022-10-31 13:58 UTC, NiedzwiedzIT reviewed
Пофіксив w wszystko ))

2022-10-31 13:58 UTC, NiedzwiedzIT commented on src/sass/_header.scss
> +.menu__link {
Пофіксив

2022-10-31 15:09 UTC, uvchuk approved these changes

2022-10-31 15:09 UTC, merged